/*
** EPITECH PROJECT, 2020
** NWP_myteams_2019
** File description:
** All possible return codes
*/

#ifndef RETURN_CODES_H_
#define RETURN_CODES_H_

#define ERR_ALREADYCONNECTED 400
#define ERR_CHANNELEXISTS 401
#define ERR_INVALIDCOMMAND 402
#define ERR_NEEDMOREPARAMS 403
#define ERR_NOSUCHCHANNEL 404
#define ERR_NOSUCHTEAM 405
#define ERR_NOSUCHTHREAD 406
#define ERR_NOTCONNECTED 407
#define ERR_TEAMEXISTS  408
#define ERR_THREADEXISTS  409
#define ERR_TOOMANYPARAMS 410
#define ERR_USERUUID 411

#define RSP_LOGIN 500
#define RSP_LOGOUT 501
#define RSP_USE 502

#endif /* !RETURN_CODES_H_ */
