/*
** EPITECH PROJECT, 2020
** NWP_myteams_2019
** File description:
** All possible return codes
*/

#ifndef RETURN_CODES_H_
#define RETURN_CODES_H_

#define ERR_ALREADYCONNECTED 400
#define ERR_ALREADYSUBBED 401
#define ERR_CHANNELEXISTS 402
#define ERR_INVALIDCOMMAND 403
#define ERR_NEEDMOREPARAMS 404
#define ERR_NOSUCHCHANNEL 405
#define ERR_NOSUCHTEAM 406
#define ERR_NOSUCHTHREAD 407
#define ERR_NOTCONNECTED 408
#define ERR_NOTSUBBED 409
#define ERR_TEAMEXISTS  410
#define ERR_THREADEXISTS  411
#define ERR_TOOMANYPARAMS 412
#define ERR_USERUUID 413

#define RSP_LOGIN 500
#define RSP_LOGOUT 501
#define RSP_SUBSCRIBE 502
#define RSP_UNSUBSCRIBE 503
#define RSP_USE 504

#endif /* !RETURN_CODES_H_ */
